antiplagiarism/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from antiplagiarism.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('search_plagiarism.urls', 'search_plagiarism'), namespace='search_plagiarism'))
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

search_plagiarism/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path

from .views import *


urlpatterns = [
    path('', index_upload_image, name='upload_image'),
    path('', display_similar_images, name='display'),
    path('result/', display_similar_images, name='display'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_plagiarism/models.py
from django.db import models
import os
import json
from antiplagiarism.settings import MEDIA_URL, DEBUG
from .search_module import similar_image_finder as sif


if DEBUG:
    from dotenv import load_dotenv
    load_dotenv('env_keys.env')

database_url = os.environ['DATABASE_URL']
imgur_client_id = os.environ['IMGUR_CLIENT_ID']


class UploadedImage(models.Model):
    image = models.ImageField(upload_to='uploaded/', null=True, blank=True)
    similar_images_list = models.CharField(max_length=1000, default='{}')
    probability_list = models.CharField(max_length=1000, default='{}')

    def __str__(self):
        return self.get_image_url()

    def get_images_probability_list(self):
        sif_obj = sif.SimilarImageFinder(database_url, imgur_client_id)
        path = MEDIA_URL + self.get_image_url()
        path = path[1:]
        images_probability_array = sif_obj.find_similar_images(path, 10)

        images_list = images_probability_array[0].tolist()
        probability_list = images_probability_array[1].tolist()

        for i in range(len(probability_list) - 1):
            probability_list[i] = (1 - probability_list[i]) * 100
        return [images_list, probability_list]

    def set_similar_images_list(self, images_list):
        imgur_images_list = []
        for i in range(len(images_list) - 1):
            imgur_images_list.append(images_list[i].replace('\n', ''))
        self.similar_images_list = json.dumps(imgur_images_list)
        self.save()

    def get_similar_images_list(self):
        return json.loads(self.similar_images_list)

    def set_probability_list(self, probability_list):
        self.images_probability_list = json.dumps(probability_list)
        self.save()

    def get_probability_list(self):
        return json.loads(self.probability_list)

    def start_finding(self):
        images_probability = self.get_images_probability_list()
        images = images_probability[0]
        probability = images_probability[1]
        self.set_similar_images_list(images)
        self.set_probability_list(probability)

    def get_image_url(self):
        return self.image.name


obj = UploadedImage()

search_plagiarism/forms.py
from django import forms
from search_plagiarism.models import UploadedImage


class UploadedImageForm(forms.ModelForm):
    class Meta:
        model = UploadedImage
        fields = ('image',)


class SimilarImagesForm(forms.ModelForm):
    class Meta:
        model = UploadedImage
        fields = ('similar_images_list',)

search_plagiarism/views.py
from django.shortcuts import render
from django.http import JsonResponse

from .models import *
from search_plagiarism.forms import UploadedImageForm, SimilarImagesForm


def index_upload_image(request):
    if request.method == 'POST':
        form = UploadedImageForm(request.POST, request.FILES, )
        if form.is_valid():
            img = form.cleaned_data.get('image')
            obj.image = img
            obj.save()
            return render(request, 'search_plagiarism/process.html')
    else:
        return render(request, 'search_plagiarism/index.html')


def display_similar_images(request):
    if request.method == 'GET':
        return render(request, 'search_plagiarism/result.html')
    else:
        obj.start_finding()
    return render(request, 'search_plagiarism/result.html',
                  {'uploaded_image': obj.image, 'similar_images': obj.get_similar_images_list(),
                   'probability': obj.get_probability_list()})

process_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <style>
        a {
            text-decoration: none;
            /* Отменяем подчеркивание у ссылки */
        }
    </style>
    <title>Сайт по поиску плагиата</title>

    <script>
        async function sendImage(form) {
            event.preventDefault();
            const scriptURL = "";

            var loading = document.createElement('div')
            loading.classList.add('lds-facebook');
            loading.innerHTML = "<div></div><div></div><div></div>"
            document.getElementById('top').appendChild(loading);
            //alert("Изображение отправлено на проверку");

            let response = await fetch(scriptURL, {
                method: 'POST',
                body: new FormData(form)
            })

            let result = await response.json();
            document.getElementById('result').innerHTML = result.message; //сервер должен вернуть ответ в формате "{message:'Ваше изображение - фейк'}"

            document.getElementById('top').querySelector('lds-facebook').remove()
        }

        function renderImage(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#render').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        }
    </script>
</head>

<body>
    <header>
        <div id="logo" onclick="slowScroll('#top')">
            <a href="#top" title="Anti-plagiarism paintings" onclick="slowScroll('#top')">Anti-plagiarism paintings</a>

        </div>
        <div id="about">
            <a href="#main" title="Описание системы" onclick="slowScroll('#main')">Описание системы</a>
           <!-- <a href="#contacts" title="Контакты" onclick="slowScroll('#contact')">Контакты</a>
            <a href="#faq" title="FAQ" onclick="slowScroll('#faq')">FAQ</a>-->
        </div>
    </header>
    <div id="top">
        {% block content %} {% endblock content %}
    </div>





    </div>
    <div id="main">
        <div class="intro">
            <h3>Описание системы созданной при помощи нейронной сети: </h3>
        </div>
        <div class="text">
            <span>Разнообразный и богатый опыт сложившаяся структура организации в значительной степени
                обуславливает создание системы обучения кадров, соответствует насущным потребностям.
                Повседневная практика показывает, что постоянное информационно-пропагандистское обеспечение
                нашей деятельности обеспечивает широкому кругу (специалистов)
                участие в формировании существенных финансовых и административных условий.</span>
        </div>

    </div>

   <!-- <div id="contacts">
        <center>
            <h5>Обратная связь</h5>
        </center>
        <form id="form_input" action="" method="">
            <div class="wrapper">
                <label for="name">Имя: <span>*</span></label><br>
                <input type="text" placeholder="Введите имя: " name="name" id="name"><br>
                <label for="email">Адрес электронной почты: <span>*</span></label><br>
                <input type="email" placeholder="Введите email: " name="email" id="email"><br>
                <label for="message">Сообщение: <span>*</span></label><br>
                <textarea placeholder="Введите ваше сообщение: " name="message" id="message"></textarea><br>
                
                <button type="submit">Отправить</button>
                <div id="mess_send" class="btn">Отправить </div>
            </div>
        </form>
    </div>
    <div id="faq">

        <h6>Frequently Asked Questions</h6>
        <div class="wrapper">
            <div>
                <span class="title">Когда работы над сайтом будут завершены?</span>
                <p>Мы прилагаем все усилия, чтобы добавить как можно больше контента. Мы не едим и не спим уже очень
                    давно,
                    мы забыли лица некоторых членов нашей семьи, но не волнуйтесь, скоро все будет готово.</p>
            </div>
            <div><span class="title">Могу ли я обратиться к вам по поводу рекламы?</span>
                <p>Мы еще не до конца запустили процесс рекламного взаимодействия, но мы постоянно находимся в поиске
                    партнеров.
                    Отправьте нам письмо по электронной почте со страницы “Обратная связь”.</p>
            </div>
            <div><span class="title">Кто ваши разработчики?</span>
                <p>Наши разработчики – это студенты Моковского Политехнического университета.
                    Они молоды и добились определенных успехов в веб-пространстве и в обучении нейронных сетей.</p>
            </div>
        </div>


    </div>-->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        function slowScroll(id) {
            $('html, body').animate({
                scrollTop: $(id).offset().top
            }, 500);

            $(document).on("scroll", function () {
                if ($(window).scrollTop() === 0)
                    $("header").removeClass("fixed");
                else
                    $("header").attr("class", "fixed");
            });
    </script>
</body>

</html>

search_plagiarism/templates/search_plagiarism/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}">
    <style>
        a {
            text-decoration: none;
            /* Отменяем подчеркивание у ссылки */
        }
    </style>
    <title>Анти-плагиат изображений</title>
</head>

<body>
    <header>
        <div id="logo">
            <a href="#top" title="Anti-plagiarism paintings">Поиск плагиата</a>

        </div>
        <div id="about">
            <a href="#main" title="Описание системы">Описание системы</a>
           <!-- <a href="#contacts" title="Контакты" onclick="slowScroll('#contact')">Контакты</a>
            <a href="#faq" title="FAQ" onclick="slowScroll('#faq')">FAQ</a>-->
        </div>
    </header>
    <div id="top">
        <h2>Система распознания картин на подлиность</h2>
        {% block content %} {% endblock content %}
    </div>

    </div>
    <div id="main">
        <div class="intro">
            <h3>Описание системы созданной при помощи нейронной сети: </h3>
        </div>
        <div class="text">
           <span>Для проверки изображения: система получает изображение, оно сжимается до 299 на 299 пикселей и
                подаётся на вход нейронной сети, откуда получается вектор массив из 131072 чисел float.
                Потом начинает скачивать блоками данные из базы данных и искать среди них ближайших.
                Когда все данные будут проверены, на выходе останется массив с 10 (или другое число) похожими картинами,
                которые уже передаются на сайт.
                Для хранения изображения: от пользователя система получает изображение,
                оно сжимается до 299 на 299 пикселей и подаётся на вход нейронной сети,
                откуда получается вектор массив из 131072 чисел float.
                Потом изображение отправляется на imgur.com, откуда получается id изображения.
                Теперь есть id и вектор(массив). Это отправляется в БД!</span>
        </div>

    </div>

   <!-- <div id="contacts">
        <center>
            <h5>Обратная связь</h5>
        </center>
        <form id="form_input" action="" method="">
            <div class="wrapper">
                <label for="name">Имя: <span>*</span></label><br>
                <input type="text" placeholder="Введите имя: " name="name" id="name"><br>
                <label for="email">Адрес электронной почты: <span>*</span></label><br>
                <input type="email" placeholder="Введите email: " name="email" id="email"><br>
                <label for="message">Сообщение: <span>*</span></label><br>
                <textarea placeholder="Введите ваше сообщение: " name="message" id="message"></textarea><br>
                
                <button type="submit">Отправить</button>
                <div id="mess_send" class="btn">Отправить </div>
            </div>
        </form>
    </div>
    <div id="faq">

        <h6>Frequently Asked Questions</h6>
        <div class="wrapper">
            <div>
                <span class="title">Когда работы над сайтом будут завершены?</span>
                <p>Мы прилагаем все усилия, чтобы добавить как можно больше контента. Мы не едим и не спим уже очень
                    давно,
                    мы забыли лица некоторых членов нашей семьи, но не волнуйтесь, скоро все будет готово.</p>
            </div>
            <div><span class="title">Могу ли я обратиться к вам по поводу рекламы?</span>
                <p>Мы еще не до конца запустили процесс рекламного взаимодействия, но мы постоянно находимся в поиске
                    партнеров.
                    Отправьте нам письмо по электронной почте со страницы “Обратная связь”.</p>
            </div>
            <div><span class="title">Кто ваши разработчики?</span>
                <p>Наши разработчики – это студенты Моковского Политехнического университета.
                    Они молоды и добились определенных успехов в веб-пространстве и в обучении нейронных сетей.</p>
            </div>
        </div>


    </div>-->

</body>

</html>

search_plagiarism/templates/search_plagiarism/index.html
{% extends "search_plagiarism/base.html" %}
{% block content %}

        <script  type="text/javascript"
                 src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
        </script>

        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

        <script  type="text/javascript">
            // Отображение загруженного изображения
            function renderImage(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#render').attr('src', e.target.result);
                    }

                    reader.readAsDataURL(input.files[0]); // convert to base64 string
                }
            }
        </script>

        <script  language="JavaScript">
            var flag = false;

            $("document").ready(function () {
                // проверка расширения файла при выборе файла
                $('#image_input').on('change', () => {
                    document.getElementById('result').innerHTML = "";
                    var exp = $('#image_input').val().split('.').pop().toString();
                    if (!(exp == 'png' || exp == 'jpg')) {
                        document.getElementById('result').innerHTML = "Ошибка!" + '<br/>' +
                                                        "Выберите изображения .jpg или .png";
                    }
                    else {
                        flag = true;
                    }
                });

                $('#upload_image_form').on('submit', () => {
                    const $files = $('#image_input').get(0).files

                    if ($files.length) {
                        // Reject big files
                        if ($files[0].size > $(this).data("max-size") * 1024) {
                            flag = false
                        }
                        // если все условия соблюдены, анимация отображается
                        if (flag) {
                            // Анимация загрузки
                            $('#render').remove();
                            $('#load').css("opacity", 1);
                        }
                    }
                    else {
                        flag = false;
                    }
                });
            });
            // если все условия соблюдены, файл загружается
            function boolFunction() {
                if (flag) return true;
                else return false;
            }
        </script>


        <form id="upload_image_form" method="post" enctype="multipart/form-data"
              onsubmit="return boolFunction();" action="{% url 'search_plagiarism:upload_image' %}"> {% csrf_token %}
            <p>Загрузите или перетащите картинку в формате JPEG, PNG</p>
            <p>
                <input id = "image_input" type="file" name="image"
                       accept="image/*" onchange="renderImage(this)">
                <input type="submit" value="Загрузить" id="otpr">
            </p>
        </form>
        <img id='render' src="" >
        <div id='load' align="center" style="opacity: 0">
            <lottie-player
                src="https://assets4.lottiefiles.com/private_files/lf30_H8JIIY.json"
                background="transparent"
                speed="1"
                style="width: 200px; height: 200px;"
                loop
                autoplay>
            </lottie-player>
        </div>
        <div id="result"></div>
{% endblock content %}

search_plagiarism/templates/search_plagiarism/process.html
{% extends "search_plagiarism/base.html" %}
{% block content %}
        <script  type="text/javascript"
                 src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
        </script>
        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

        <script  language="JavaScript">
            $("document").ready(function () {
                $('#start_form').on('submit', () => {
                    $('#load1').css("opacity", 1);
                });
            });
        </script>


    <div id="ptext">Изображение загружено</div>
    <form id="start_form" method="post" enctype="multipart/form-data"
          action="{% url 'search_plagiarism:display' %}">{% csrf_token %}
        <input type="submit" id="otpr1" value="Начать поиск">
    </form>

    <div align="center" id='load1' style="opacity: 0">
        <lottie-player
            src="https://assets4.lottiefiles.com/private_files/lf30_H8JIIY.json"
            background="transparent"
            speed="1"
            style="width: 200px; height: 200px;"
            loop
            autoplay>
        </lottie-player>
    </div>



{% endblock content %}

search_plagiarism/templates/search_plagiarism/result.html
{% extends "search_plagiarism/base.html" %}
{% block content %}

    <form method="get" enctype="multipart/form-data"
          action="{% url 'search_plagiarism:display' %}" >{% csrf_token %}
        <p>Загруженное изображение</p>
        <p>
            <img src="..{{MEDIA_URL}}{{ uploaded_image }}">
        </p>
        <p>Результаты поиска</p>
        <p>
            {% for similar_image in similar_images %}
                <img src="{{ similar_image }}">
            {% endfor %}
        </p>

    </form>

{% endblock content %}